version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    container_name: rtr_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: readtherules
    ports:
      - "5432:5432"
    volumes:
      - rtr_db_data:/var/lib/postgresql/data

volumes:
  rtr_db_data: {}